-- Auto-generated by Omarchy
local M = {}

M.font = "JetBrainsMono Nerd Font"

M.colors = {
  foreground = "#f2ddc2",
  background = "#1a1a1c",

  cursor_bg = "#f2ddc2",
  cursor_fg = "#1a1a1c",
  cursor_border = "#f2ddc2",

  selection_fg = "#1a1a1c",
  selection_bg = "#2e2e30",

  split = "#ba8d22",

  ansi = {
    "#1a1a1c",
    "#f79605",
    "#d7be67",
    "#f5c651",
    "#cbb15b",
    "#e7b211",
    "#f9e198",
    "#fdf5a7",
  },

  brights = {
    "#ba8d22",
    "#f5dc89",
    "#f6e79d",
    "#fee4a4",
    "#d5d5dc",
    "#f8f8f8",
    "#e5eae9",
    "#f2ddc2",
  },

  tab_bar = {
    background = "#1a1a1c",

    active_tab = {
      bg_color = "#1a1a1c",
      fg_color = "#f2ddc2",
      intensity = "Bold",
    },

    inactive_tab = {
      bg_color = "#1d1d1f",
      fg_color = "#d4bfa4",
    },

    inactive_tab_hover = {
      bg_color = "#212123",
      fg_color = "#f2ddc2",
    },

    new_tab = {
      bg_color = "#1f1f21",
      fg_color = "#d4bfa4",
    },

    new_tab_hover = {
      bg_color = "#262628",
      fg_color = "#f2ddc2",
    },
  },
}

M.window_frame = {
  active_titlebar_bg = "#1a1a1c",
  inactive_titlebar_bg = "#1a1a1c",
}

return M
