-- Auto-generated by Omarchy
local M = {}

M.font = "JetBrainsMono Nerd Font"

M.colors = {
  foreground = "#f8f8f8",
  background = "#1a1a1c",

  cursor_bg = "#f8f8f8",
  cursor_fg = "#1a1a1c",
  cursor_border = "#f8f8f8",

  selection_fg = "#1a1a1c",
  selection_bg = "#2e2e30",

  split = "#ba8d22",

  ansi = {
    "#1a1a1c",
    "#f79605",
    "#d7be67",
    "#f5c651",
    "#cbb15b",
    "#b6afb6",
    "#b3c1bc",
    "#FDF5A7",
  },

  brights = {
    "#ba8d22",
    "#f5dc89",
    "#f6e79d",
    "#fee4a4",
    "#d5d5dc",
    "#e2dfe2",
    "#e5eae9",
    "#f8f8f8",
  },

  tab_bar = {
    background = "#1a1a1c",

    active_tab = {
      bg_color = "#1a1a1c",
      fg_color = "#f8f8f8",
      intensity = "Bold",
    },

    inactive_tab = {
      bg_color = "#1d1d1f",
      fg_color = "#dadada",
    },

    inactive_tab_hover = {
      bg_color = "#212123",
      fg_color = "#f8f8f8",
    },

    new_tab = {
      bg_color = "#1f1f21",
      fg_color = "#dadada",
    },

    new_tab_hover = {
      bg_color = "#262628",
      fg_color = "#f8f8f8",
    },
  },
}

M.window_frame = {
  active_titlebar_bg = "#1a1a1c",
  inactive_titlebar_bg = "#1a1a1c",
}

return M
